#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

# if [ "$branch" = "master" ]; then
if [ "$branch" = "master" ] || [ "$branch" = "dev" ]; then
  echo "master와 dev에는 바로 push할 수 없습니다. feat에서 dev로 pull request하세요."
  exit 1
fi