name: Deploy to AWS S3

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 코드
        uses: actions/checkout@v2

      - name: Node 설치
        uses: actions/setup-node@v2
        with:
          node-version: 18 # 필요한 Node.js 버전으로 변경

      - name: 의존성 설치
        run: yarn install

      - name: React 코드 빌드
        run: yarn build

      - name: Deploy to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2 # S3 버킷의 지역에 맞게 변경
        run: |
          aws s3 sync build/ s3://withme-sesac/
          aws s3 website s3://withme-sesac/ --index-document index.html --error-document 404.html
          aws s3api put-object-acl --bucket withme-sesac --key index.html --acl public-read
