name: prod AWS S3 배포

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 코드
        uses: actions/checkout@v2

      - name: Node 설치
        uses: actions/setup-node@v2
        with:
          node-version: 18 # 필요한 Node.js 버전으로 변경

      - name: 의존성 설치
        run: yarn install

      - name: React 코드 빌드
        run: yarn build

      - name: Create Versioned Folder
        run: |
          DATE=$(date +'%Y-%m-%d-%H-%M')
        # 현재 날짜를 YYYY-MM-DD 형식으로 가져옵니다.

      - name: Deploy to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2 # S3 버킷의 지역에 맞게 변경
        run: |
          aws s3 mv s3://withme-sesac/ s3://withme-sesac/dist/$DATE/ --recursive  
          aws s3 sync dist/ s3://withme-sesac/
          aws s3 website s3://withme-sesac/ --index-document index.html --error-document 404.html
          aws s3api put-bucket-acl --bucket withme-sesac --acl public-read
        # 기존 S3 객체를 날짜 폴더로 이동시킵니다.
        # 새로 빌드한 파일을 S3에 업로드합니다.
        # S3 웹사이트 설정을 업데이트합니다.
        # public-read ACL을 설정합니다.
